/**
* Autogenerated by hasi at 2018-07-27 18:57:40
*
* DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
#import <Foundation/Foundation.h>
#import "MomApi.h"
//@implementation VideoClassify
//@end
